#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# -- Create paraview file
paraFoam -builtin -touch

./iPFrun

# -- Create mesh
#runApplication blockMesh

# -- Add internal patch
runApplication addEmptyPatch internalPatch internal -overwrite

# -- Decompose the case
runApplication decomposePar

# -- run the calc
runParallel $(getApplication)

# -- Reconstruct the case
runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
